In [2]:
import numpy as np
import pandas as pd

In [3]:
a = pd.read_feather(rf"/root/autodl-fs/lingqiData/debug/20260805/data10d/factors/accumulation_distribution_20.fea")
a

Code,000001,000002,000006,000008,000009,000012,000021,000025,000027,000028,...,603978,603979,603982,603985,603986,603989,603990,603993,603995,603997
Date,,,,,,,,,,,,,,,,,,,,,
20260722,0.876404,0.771910,0.219663,0.023596,0.462921,0.592697,0.248315,0.264045,0.860112,0.721348,...,0.161798,0.826404,0.208989,0.040449,0.269663,0.083708,0.193820,0.443820,0.294382,0.305056
20260723,0.929134,0.772778,0.255906,0.050619,0.450506,0.504499,0.157480,0.427447,0.880202,0.696288,...,0.206974,0.917323,0.267154,0.062430,0.117548,0.039933,0.228346,0.444319,0.222722,0.324522
20260724,0.934795,0.729061,0.308600,0.039910,0.515458,0.521641,0.243957,0.311411,0.932546,0.669477,...,0.258010,0.940416,0.304666,0.055649,0.119168,0.012929,0.219786,0.525014,0.290613,0.350197
20260727,0.927447,0.749156,0.280090,0.012373,0.519123,0.609674,0.210349,0.496625,0.925197,0.648481,...,0.137795,0.944319,0.253093,0.083802,0.070304,0.021372,0.273903,0.439258,0.358830,0.267154
20260728,0.971235,0.820079,0.246475,0.055838,0.544839,0.411168,0.121827,0.373942,0.931754,0.681331,...,0.071066,0.967851,0.291032,0.068246,0.073322,0.023125,0.243655,0.388607,0.269600,0.254935
20260729,0.957159,0.866404,0.316798,0.027621,0.630778,0.317362,0.142052,0.366404,0.929538,0.689402,...,0.031003,0.968433,0.319617,0.023675,0.083991,0.023112,0.319053,0.381060,0.303269,0.217024
20260730,0.983137,0.875773,0.282743,0.038224,0.854975,0.200112,0.151209,0.641372,0.960090,0.669477,...,0.014053,0.941540,0.316470,0.029230,0.143901,0.021360,0.310849,0.303541,0.254637,0.268690
20260731,0.995217,0.916151,0.296567,0.070343,0.978053,0.076533,0.087226,0.607203,0.945414,0.586944,...,0.027575,0.938098,0.307822,0.080473,0.101857,0.005346,0.258863,0.428813,0.249859,0.406303
20260803,0.995219,0.965129,0.332958,0.042745,0.944882,0.141732,0.059055,0.727222,0.969629,0.341395,...,0.077053,0.939820,0.371204,0.106299,0.046119,0.005343,0.115298,0.464567,0.174916,0.359955
20260804,0.982535,0.945352,0.383662,0.005352,0.971268,0.180845,0.037183,0.800000,0.986479,0.302535,...,0.080563,0.921690,0.456338,0.117746,0.042817,0.014648,0.151549,0.537465,0.153239,0.300282

In [4]:
a = pd.read_parquet(rf"/root/autodl-fs/lingqiData/debug/20260805/data10d/raw/cyq_chips/000001.SZ.parquet")
a

     trade_date stock_code  price  percent
0    2026-07-22  000001.SZ    0.2     0.01
1    2026-07-22  000001.SZ    0.4     0.01
2    2026-07-22  000001.SZ    0.6     0.02
3    2026-07-22  000001.SZ    0.8     0.01
4    2026-07-22  000001.SZ    1.0     0.01
...         ...        ...    ...      ...
1035 2026-08-04  000001.SZ   15.0     0.10
1036 2026-08-04  000001.SZ   15.2     0.10
1037 2026-08-04  000001.SZ   15.6     0.10
1038 2026-08-04  000001.SZ   10.6    17.60
1039 2026-08-04  000001.SZ    0.2     0.01

[1040 rows x 4 columns]

In [5]:
a = pd.read_parquet(rf"/root/autodl-fs/lingqiData/debug/20260805/data10d/raw/daily.parquet")
a

,stock_code,trade_date,open,high,low,close,pre_close,change,pct_chg,vol,amount,stock_name,ah_vol,ah_amount
0,000001.SZ,2026-07-22,10.81,10.98,10.77,10.98,10.84,0.14,1.29,1.029484e+08,1.120151e+09,平安银行,NaN,NaN
1,000001.SZ,2026-07-23,10.92,11.12,10.90,11.08,10.98,0.10,0.91,1.095743e+08,1.210838e+09,平安银行,NaN,NaN
2,000001.SZ,2026-07-24,11.09,11.18,11.09,11.10,11.08,0.02,0.18,1.140933e+08,1.269361e+09,平安银行,NaN,NaN
3,000001.SZ,2026-07-27,11.11,11.16,11.04,11.11,11.10,0.01,0.09,9.571555e+07,1.062796e+09,平安银行,NaN,NaN
4,000001.SZ,2026-07-28,11.10,11.21,11.09,11.20,11.11,0.09,0.81,1.061011e+08,1.185515e+09,平安银行,66900.0,749280.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44024,920992.BJ,2026-07-29,11.20,11.53,11.13,11.51,11.25,0.26,2.31,9.304831e+05,1.056808e+07,中科美菱,0.0,0.0
44025,920992.BJ,2026-07-30,11.42,11.72,11.30,11.45,11.51,-0.06,-0.52,8.004929e+05,9.232127e+06,中科美菱,0.0,0.0
44026,920992.BJ,2026-07-31,11.54,12.00,11.46,11.66,11.45,0.21,1.83,7.544849e+05,8.779091e+06,中科美菱,0.0,0.0
44027,920992.BJ,2026-08-03,11.68,11.68,11.48,11.56,11.66,-0.10,-0.86,7.543200e+05,8.714102e+06,中科美菱,0.0,0.0
44028,920992.BJ,2026-08-04,11.63,11.83,11.57,11.73,11.56,0.17,1.47,9.356600e+05,1.094232e+07,中科美菱,0.0,0.0